[tool.poetry]
name = "poetry-lock-package"
version = "0.1.0"
description = "Poetry lock package generator"
authors = ["Bram Neijt <bram@neijt.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
toml = "^0.10.2"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
poetry-lock-package = 'poetry_lock_package.app:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
