[tool.poetry]
name = "poetry-lock-package"
version = "0.0.1"
description = "Poetry lock package generator"
authors = ["Bram Neijt <bram@neijt.nl>"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/bneijt/poetry-lock-package"

[tool.poetry.dependencies]
python = "~2.7 || ^3.7"
poetry = "^1.2"
importlib-metadata = { version = ">=0.22", python = "<3.8" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b1"
rope = "^0.18.0"
twine = "^3.4.1"
pre-commit = "^2.12.0"

[tool.poetry.plugins."poetry.application.plugin"]
poetry-lock-package = "poetry_lock_package.plugin:BuildLockApplicationPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
